services:
  chat2api:
    build:
      context: https://github.com/Seaking111/chat2api-docker.git#main
    container_name: chat2api
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
